/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Harshit_Calculator;

import javax.swing.JOptionPane;
import java.util.Arrays;


/**
 *
 * @author rajh8
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtUser = new javax.swing.JTextField();
        jtLogin = new javax.swing.JButton();
        jtPass = new javax.swing.JPasswordField();
        jtShow = new javax.swing.JCheckBox();
        jtExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("HARSHIT CALCULATOR LOGIN PAGE");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("PASSWORD");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 80, 30));

        jLabel3.setBackground(new java.awt.Color(102, 255, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("USER NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 80, 30));

        jtUser.setBackground(new java.awt.Color(255, 255, 102));
        jtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtUserActionPerformed(evt);
            }
        });
        getContentPane().add(jtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 230, -1));

        jtLogin.setBackground(new java.awt.Color(102, 255, 102));
        jtLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtLogin.setText("Login");
        jtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        jtPass.setBackground(new java.awt.Color(255, 255, 51));
        jtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPassActionPerformed(evt);
            }
        });
        getContentPane().add(jtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 230, -1));

        jtShow.setText("Show Password");
        jtShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtShowActionPerformed(evt);
            }
        });
        getContentPane().add(jtShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 130, -1));

        jtExit.setBackground(new java.awt.Color(255, 51, 51));
        jtExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtExit.setText("EXIT");
        jtExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtExitActionPerformed(evt);
            }
        });
        getContentPane().add(jtExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        pack();
    }// </editor-fold>                        

    private void jtUserActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void jtLoginActionPerformed(java.awt.event.ActionEvent evt) {                                        
      
        if(jtUser.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please fill out username");
        }
        else if (jtPass.getPassword().length == 0) {
    JOptionPane.showMessageDialog(null, "Please fill out password");
}

        else if (jtUser.getText().contains("Harshit") && jtPass.getText().contains("12345678")){
            JOptionPane.showMessageDialog(null,"Login Succesful");
            Harshit_Calculator Calculator=new Harshit_Calculator();
            Calculator.setVisible(true);
        }
        else {
         JOptionPane.showMessageDialog(null,"Wrong username or password !!","Message",JOptionPane.ERROR_MESSAGE);

        }
    }                                       

    private void jtPassActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void jtShowActionPerformed(java.awt.event.ActionEvent evt) {                                       
        
        if(jtShow.isSelected()){
            jtPass.setEchoChar((char)0);
        }
        else {
            jtPass.setEchoChar('*');
        }
    }                                      

    private void jtExitActionPerformed(java.awt.event.ActionEvent evt) {                                       
      System.exit(0);
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jtExit;
    private javax.swing.JButton jtLogin;
    private javax.swing.JPasswordField jtPass;
    private javax.swing.JCheckBox jtShow;
    private javax.swing.JTextField jtUser;
    // End of variables declaration                   
}
